version: 2

builds:
  - env: [CGO_ENABLED=0]
    goos: [linux, windows, darwin]
    goarch: [amd64, arm64]
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - format_overrides:
      - goos: windows
        format: zip

brews:
  - repository:
      owner: riccardomerenda
      name: homebrew-tap
    homepage: https://github.com/riccardomerenda/logq
    description: "Fast, interactive log explorer for the terminal"
    license: "MIT"
    install: |
      bin.install "logq"
    test: |
      system "#{bin}/logq", "--version"

scoops:
  - repository:
      owner: riccardomerenda
      name: scoop-bucket
    homepage: https://github.com/riccardomerenda/logq
    description: "Fast, interactive log explorer for the terminal"
    license: "MIT"

release:
  github:
    owner: riccardomerenda
    name: logq
